"""init migration

Revision ID: 2716a89f7392
Revises: ee3ed024b54b
Create Date: 2016-07-10 01:31:15.621000

"""

# revision identifiers, used by Alembic.
revision = '2716a89f7392'
down_revision = 'ee3ed024b54b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderListDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderlistid', sa.Integer(), nullable=False),
    sa.Column('foodid', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['foodid'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['orderlistid'], ['orderlists.id'], ),
    sa.PrimaryKeyConstraint('id', 'orderlistid', 'foodid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderListDetails')
    ### end Alembic commands ###
