"""third migration

Revision ID: 3550338572e5
Revises: a16533d53369
Create Date: 2016-07-10 16:50:13.871839

"""

# revision identifiers, used by Alembic.
revision = '3550338572e5'
down_revision = 'a16533d53369'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
