"""chage order

Revision ID: 3c42898c9b8a
Revises: bf11456e9f25
Create Date: 2016-07-11 21:14:12.877289

"""

# revision identifiers, used by Alembic.
revision = '3c42898c9b8a'
down_revision = 'bf11456e9f25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderlists', sa.Column('scores', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('headimgurl', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('identity', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    op.drop_column('users', 'identity')
    op.drop_column('users', 'headimgurl')
    op.drop_column('orderlists', 'scores')
    ### end Alembic commands ###
