"""fix bugs

Revision ID: 3f059b33aaea
Revises: 6b33b9c8e601
Create Date: 2016-07-12 12:56:48.367204

"""

# revision identifiers, used by Alembic.
revision = '3f059b33aaea'
down_revision = '6b33b9c8e601'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderlists', sa.Column('discount', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderlists', 'discount')
    ### end Alembic commands ###
