"""init migration

Revision ID: 4924455c3a76
Revises: 3550338572e5
Create Date: 2016-07-10 19:54:26.533000

"""

# revision identifiers, used by Alembic.
revision = '4924455c3a76'
down_revision = '3550338572e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageurl', sa.String(length=256), nullable=True),
    sa.Column('foodid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topofficials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageurl', sa.String(length=256), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topofficials')
    op.drop_table('foodimages')
    ### end Alembic commands ###
