"""init migration

Revision ID: 58291e445224
Revises: e81122219d40
Create Date: 2016-07-10 01:23:11.482000

"""

# revision identifiers, used by Alembic.
revision = '58291e445224'
down_revision = 'e81122219d40'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customerusers', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customerusers', sa.Column('test', mysql.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
