"""nn

Revision ID: 6b33b9c8e601
Revises: 3c42898c9b8a
Create Date: 2016-07-11 21:28:02.886581

"""

# revision identifiers, used by Alembic.
revision = '6b33b9c8e601'
down_revision = '3c42898c9b8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'foodimages', 'foods', ['foodid'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foodimages', type_='foreignkey')
    ### end Alembic commands ###
