"""init migration

Revision ID: 6b341f775d64
Revises: 2716a89f7392
Create Date: 2016-07-10 16:13:13.362000

"""

# revision identifiers, used by Alembic.
revision = '6b341f775d64'
down_revision = '2716a89f7392'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messuredatas')
    op.drop_column('customerusers', 'test')
    op.add_column('foods', sa.Column('disable', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('personprice', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('scoles', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scoles')
    op.drop_column('users', 'personprice')
    op.drop_column('users', 'location')
    op.drop_column('foods', 'disable')
    op.add_column('customerusers', sa.Column('test', mysql.VARCHAR(length=32), nullable=True))
    op.create_table('messuredatas',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('instrumentid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('datatype', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentid'], [u'users.id'], name=u'messuredatas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
