"""init migration

Revision ID: 85ddd2eb4007
Revises: f65533a766d1
Create Date: 2016-07-13 21:38:16.997000

"""

# revision identifiers, used by Alembic.
revision = '85ddd2eb4007'
down_revision = 'f65533a766d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bestFoodimgurl', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('cookEnvirimgurl', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('cookLifeimgurl', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'cookLifeimgurl')
    op.drop_column('users', 'cookEnvirimgurl')
    op.drop_column('users', 'bestFoodimgurl')
    ### end Alembic commands ###
