"""init migration

Revision ID: 8aeef7366723
Revises: None
Create Date: 2016-07-10 00:51:15.369000

"""

# revision identifiers, used by Alembic.
revision = '8aeef7366723'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('discription', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('monthsales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messuredatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumentid', sa.Integer(), nullable=True),
    sa.Column('datatype', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messuredatas')
    op.drop_table('foods')
    op.drop_table('users')
    op.drop_table('customerusers')
    ### end Alembic commands ###
