"""first migration

Revision ID: 99caec519f62
Revises: None
Create Date: 2016-07-10 16:45:44.736174

"""

# revision identifiers, used by Alembic.
revision = '99caec519f62'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('description', sa.String(length=256), nullable=True))
    op.drop_column('foods', 'discription')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('discription', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('foods', 'description')
    ### end Alembic commands ###
