"""change orderList

Revision ID: 9fa10ee4fc62
Revises: 4924455c3a76
Create Date: 2016-07-10 20:28:51.464815

"""

# revision identifiers, used by Alembic.
revision = '9fa10ee4fc62'
down_revision = '4924455c3a76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderlists', sa.Column('planeattime', sa.DateTime(), nullable=True))
    op.add_column('orderlists', sa.Column('token', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderlists', 'token')
    op.drop_column('orderlists', 'planeattime')
    ### end Alembic commands ###
