"""second migration

Revision ID: a16533d53369
Revises: 99caec519f62
Create Date: 2016-07-10 16:49:33.981574

"""

# revision identifiers, used by Alembic.
revision = 'a16533d53369'
down_revision = '99caec519f62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###
