"""init migration

Revision ID: e81122219d40
Revises: None
Create Date: 2016-07-10 01:22:37.602000

"""

# revision identifiers, used by Alembic.
revision = 'e81122219d40'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customerusers', sa.Column('test', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customerusers', 'test')
    ### end Alembic commands ###
