"""init migration

Revision ID: ee3ed024b54b
Revises: 58291e445224
Create Date: 2016-07-10 01:23:34.145000

"""

# revision identifiers, used by Alembic.
revision = 'ee3ed024b54b'
down_revision = '58291e445224'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customerusers', sa.Column('test', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customerusers', 'test')
    ### end Alembic commands ###
