"""init migration

Revision ID: fb4f174dac2b
Revises: 6b341f775d64
Create Date: 2016-07-10 16:19:07.990000

"""

# revision identifiers, used by Alembic.
revision = 'fb4f174dac2b'
down_revision = '6b341f775d64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customerusers', sa.Column('friendly', sa.Float(), nullable=True))
    op.add_column('customerusers', sa.Column('honesty', sa.Float(), nullable=True))
    op.add_column('customerusers', sa.Column('passion', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customerusers', 'passion')
    op.drop_column('customerusers', 'honesty')
    op.drop_column('customerusers', 'friendly')
    ### end Alembic commands ###
